services:
  - type: web
    name: nexa-tiktok-generator
    env: python
    rootDir: tiktok_generator
    buildCommand: apt-get install -y fonts-noto-cjk && pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300 --workers 1 --bind 0.0.0.0:$PORT
